version: '2'
services:
  odoo14:
    image: odoo:14
    # container_name: odoo14
    ports:
      - "10014:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=localhost
      - POSTGRES_DB=1313odoo
      - USER=1313odoo
      - PASSWORD=52pLGrZzfZY7
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    